const FRIDAY_EVENT = 'Friday Gathering'
const SATURDAY_EVENT = 'Saturday Gathering'

const CREDITCARD_TXN_FEE = 1.24
const PAYPAY_TXN_FEE = 1.36
const EVENT_FEE = 30.00

const TXN_COMPLETED = 'Completed'

export { FRIDAY_EVENT, SATURDAY_EVENT, CREDITCARD_TXN_FEE, PAYPAY_TXN_FEE, EVENT_FEE, TXN_COMPLETED }