const FRIDAY_EVENT = 'Friday Gathering'
const SATURDAY_EVENT = 'Saturday Gathering'
const GOLF_EVENT = 'Golf Outing'
const TOUR_EVENT = 'CHS Tour'

const PREPAY_FEE = 25.00
const AT_DOOR_FEE = 30.00

const NO_CHARGE = 'na'
const PAY_AT_DOOR = 'door'
const PAY_BY_MAIL = 'mail'

const TXN_COMPLETED = 'COMPLETED'
const TXN_PAYMENT_PENDING_MAIL = 'PAYMENT PENDING - MAIL'
const TXN_PAYMENT_PENDING_DOOR = 'PAYMENT PENDING - DOOR'

export { FRIDAY_EVENT, SATURDAY_EVENT, GOLF_EVENT, TOUR_EVENT,
  PREPAY_FEE, AT_DOOR_FEE,  
  NO_CHARGE, PAY_AT_DOOR, PAY_BY_MAIL, 
  TXN_COMPLETED, TXN_PAYMENT_PENDING_MAIL, TXN_PAYMENT_PENDING_DOOR }