const SATURDAY_EVENT = '52nd Reunion Picnic'

const PREPAY_FEE = 0.00
const AT_DOOR_FEE = 0.00

const NO_CHARGE = 'na'
const PAY_AT_DOOR = 'door'
const PAY_BY_MAIL = 'mail'
const PAY_IS_PENDING = 'pending'

const TXN_COMPLETED = 'COMPLETED'
const TXN_DETAILS_PENDING = 'REGISTERED - DETAILS PENDING'
const TXN_PAYMENT_PENDING_MAIL = 'PAYMENT PENDING - MAIL'
const TXN_PAYMENT_PENDING_DOOR = 'PAYMENT PENDING - DOOR'

export { 
  SATURDAY_EVENT,
  PREPAY_FEE, AT_DOOR_FEE,  
  NO_CHARGE, PAY_AT_DOOR, PAY_BY_MAIL, PAY_IS_PENDING,
  TXN_COMPLETED, TXN_PAYMENT_PENDING_MAIL, TXN_PAYMENT_PENDING_DOOR, 
  TXN_DETAILS_PENDING
}